import type { DefectAnalysis, ResolutionResult } from '@torin/domain';

export function buildPrBody(
  defectDescription: string,
  analysis: DefectAnalysis,
  resolution: ResolutionResult
): string {
  const sections: string[] = [
    '## Defect Description',
    defectDescription,
    '',
    '## Root Cause',
    analysis.rootCause,
    '',
    '## Resolution Summary',
    resolution.summary,
  ];

  if (resolution.changes && resolution.changes.length > 0) {
    sections.push('', '## Changes');
    for (const change of resolution.changes) {
      sections.push(`### \`${change.file}\``, change.description, '');
    }
  } else {
    sections.push(
      '',
      '## Changed Files',
      ...resolution.filesChanged.map((f) => `- \`${f}\``),
      ''
    );
  }

  sections.push(
    '## Test Results',
    resolution.testsPassed ? '✅ All tests passed' : '⚠️ Some tests did not pass'
  );
  if (resolution.testOutput) {
    sections.push(
      '',
      '<details><summary>Test output</summary>',
      '',
      '```',
      resolution.testOutput,
      '```',
      '</details>'
    );
  }

  if (resolution.reviewNotes) {
    sections.push('', '## Review Notes', resolution.reviewNotes);
  }

  if (resolution.breakingChanges) {
    sections.push('', '## ⚠️ Breaking Changes', resolution.breakingChanges);
  }

  const confidenceTag = analysis.confidence
    ? ` · Confidence: ${analysis.confidence}`
    : '';
  sections.push('', '---', `🤖 Generated by Torin${confidenceTag}`);

  return sections.join('\n');
}
