import type { BugAnalysis, FixResult } from '@torin/domain';

export function buildPrBody(
  bugDescription: string,
  analysis: BugAnalysis,
  fix: FixResult
): string {
  const sections: string[] = [
    '## Bug Description',
    bugDescription,
    '',
    '## Root Cause',
    analysis.rootCause,
    '',
    '## Fix Summary',
    fix.summary,
  ];

  if (fix.changes && fix.changes.length > 0) {
    sections.push('', '## Changes');
    for (const change of fix.changes) {
      sections.push(`### \`${change.file}\``, change.description, '');
    }
  } else {
    sections.push(
      '',
      '## Changed Files',
      ...fix.filesChanged.map((f) => `- \`${f}\``),
      ''
    );
  }

  sections.push(
    '## Test Results',
    fix.testsPassed ? '✅ All tests passed' : '⚠️ Some tests did not pass'
  );
  if (fix.testOutput) {
    sections.push(
      '',
      '<details><summary>Test output</summary>',
      '',
      '```',
      fix.testOutput,
      '```',
      '</details>'
    );
  }

  if (fix.reviewNotes) {
    sections.push('', '## Review Notes', fix.reviewNotes);
  }

  if (fix.breakingChanges) {
    sections.push('', '## ⚠️ Breaking Changes', fix.breakingChanges);
  }

  const confidenceTag = analysis.confidence
    ? ` · Confidence: ${analysis.confidence}`
    : '';
  sections.push('', '---', `🤖 Generated by Torin${confidenceTag}`);

  return sections.join('\n');
}
